frase = 'Curso em Video Python'
print(frase[9])
print(frase[9:13])
print(frase[9:21])
print(frase[9:21:2])
print(frase[:5])
print(frase[9::3])
print(len(frase))
print(frase.count('o'))
print(frase.count('O'))
print(frase.count('o', 0, 13))
print(frase.find('deo'))
print(frase.find('android'))
print('Curso' in frase)
print(frase.replace('Python', 'Android'))
print(frase.upper())
print(frase.lower())
print(frase.capitalize())
print(frase.title())
print(frase.strip())
print(frase.split())
print('-' .join(frase))