lanche = ('Hambúrguer', 'Suco', 'Pizza', 'pudim')
print(lanche)
print('-=-='*10)
print(lanche[0] , '(0)')
print(lanche[1] , '(1)')
print(lanche[2] , '(2)')
print(lanche[3] , '(3)')
print('-=-='*10)
print(lanche[-1] , '(-1)')
print(lanche[-2] , '(-2)')
print(lanche[-3] , '(-3)')
print(lanche[-4] , '(-4)')
print('-=-='*10)
print(lanche[1:3])
print(lanche[2:])
print(lanche[:2])
print('-=-='*10)
print(lanche[-2:])
print(lanche[-3:])
print(lanche[:-2])
print(lanche[:-3])