a = (2, 5, 4)
b = (5, 8, 1, 2)
c = b + a
d = a + b
print('-=-=-' * 10)
print((c),' c ')
print(c.count(5))
print(c.count(4))
print(c.count(9))
print(c.index(8))
print(c.index(2))
print(c.index(2, 4))
print('-=-=-' * 10)
print((d),' d ')
print(d.count(5))
print(d.count(4))
print(d.count(9))
print(d.index(8))
print(d.index(2))
print(d.index(2, 1))
print('-=-=-' * 10)